GET http://localhost:3000/movies

###Buscar pelicula por id

GET http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

###Buscar peliculas por genero

GET http://localhost:3000/movies?genre=Drama

###Crear nueva pelicula

POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "El despertar del JEDI",
    "year": 2000,
    "director": "George Lucas",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Action",
        "Ficcion",
        "Adventure"
    ]
}

### Modificar una pelicula

PATCH http://localhost:3000/movies/887ecd60-b0f2-11ef-a3ea-0a0027000004
Content-Type: application/json

{
    "year": 1901
}


### Eliminar pelicula

DELETE http://localhost:3000/movies/891e00d6-b0f2-11ef-a3ea-0a0027000004